plugins {
    id 'java'
    id 'maven-publish'
}

group = 'net.YaRh'
version = '1.3.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
    failOnNoDiscoveredTests = false
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
            artifactId = 'convconf'
        }
    }

    repositories {
        maven {
            name = "GitHubPackages"
            url = "https://maven.pkg.github.com/Yet-Another-Rabbit-Hole/ConvenientConfiguration"

            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

tasks.register("updateLocal") {
    dependsOn testClasses
    dependsOn jar
    dependsOn javadoc
    dependsOn publishToMavenLocal
}